/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CategoryMapping {
  'category' : string,
  'subcategories' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export interface JobPost {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'workType' : string,
  'salary' : string,
  'area' : string,
  'description' : string,
  'phone' : string,
  'dateTime' : Time,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker {
  'id' : bigint,
  'status' : WorkerStatus,
  'verified' : boolean,
  'featured' : boolean,
  'subcategory' : string,
  'area' : string,
  'userId' : Principal,
  'name' : string,
  'experience' : string,
  'workingHours' : string,
  'category' : string,
  'comments' : [] | [string],
  'phone' : string,
  'photo' : ExternalBlob,
}
export type WorkerStatus = { 'pendingVerification' : null } |
  { 'approved' : null } |
  { 'rejected' : string };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveJobPost' : ActorMethod<[bigint], boolean>,
  'approveWorker' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJobPost' : ActorMethod<
    [string, string, Time, string, string, string],
    string
  >,
  'featureWorker' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<CategoryMapping>>,
  'getAllJobPosts' : ActorMethod<[], Array<JobPost>>,
  'getAllWorkers' : ActorMethod<[], Array<Worker>>,
  'getApprovedJobs' : ActorMethod<[], Array<JobPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryBySubcategory' : ActorMethod<[string], [] | [string]>,
  'getFeaturedWorkers' : ActorMethod<[], Array<Worker>>,
  'getJobPostById' : ActorMethod<[bigint], [] | [JobPost]>,
  'getPendingJobPosts' : ActorMethod<[], Array<JobPost>>,
  'getPendingWorkers' : ActorMethod<[], Array<Worker>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerById' : ActorMethod<[bigint], [] | [Worker]>,
  'getWorkersByCategory' : ActorMethod<[string], Array<Worker>>,
  'getWorkersBySubcategory' : ActorMethod<[string], Array<Worker>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markWorkerVerified' : ActorMethod<[bigint], undefined>,
  'rejectJobPost' : ActorMethod<[bigint], boolean>,
  'rejectWorker' : ActorMethod<[bigint, string], boolean>,
  'repairDataIntegrity' : ActorMethod<[], string>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchWorkersByArea' : ActorMethod<[string], Array<Worker>>,
  'searchWorkersByAreaAndCategory' : ActorMethod<
    [string, string],
    Array<Worker>
  >,
  'searchWorkersByAreaAndSubcategory' : ActorMethod<
    [string, string],
    Array<Worker>
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitWorkerRegistration' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      ExternalBlob,
      [] | [string],
    ],
    string
  >,
  'unfeatureWorker' : ActorMethod<[bigint], undefined>,
  'upgradeToAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];