/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CategoryMapping = IDL.Record({
  'category' : IDL.Text,
  'subcategories' : IDL.Vec(IDL.Text),
});
export const JobPost = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'workType' : IDL.Text,
  'salary' : IDL.Text,
  'area' : IDL.Text,
  'description' : IDL.Text,
  'phone' : IDL.Text,
  'dateTime' : Time,
});
export const WorkerStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Worker = IDL.Record({
  'id' : IDL.Nat,
  'status' : WorkerStatus,
  'verified' : IDL.Bool,
  'featured' : IDL.Bool,
  'subcategory' : IDL.Text,
  'area' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'experience' : IDL.Text,
  'workingHours' : IDL.Text,
  'category' : IDL.Text,
  'comments' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'photo' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveJobPost' : IDL.Func([IDL.Nat], [], []),
  'approveWorker' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJobPost' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'featureWorker' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(CategoryMapping)], []),
  'getAllJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getApprovedJobs' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryBySubcategory' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getFeaturedWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getJobPostById' : IDL.Func([IDL.Nat], [IDL.Opt(JobPost)], ['query']),
  'getPendingJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
  'getPendingWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getSafeCategoryWorkers' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerById' : IDL.Func([IDL.Nat], [IDL.Opt(Worker)], ['query']),
  'getWorkersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
  'getWorkersBySubcategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Worker)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWorkerVerified' : IDL.Func([IDL.Nat], [], []),
  'rejectJobPost' : IDL.Func([IDL.Nat], [], []),
  'rejectWorker' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'repairDataIntegrity' : IDL.Func([], [IDL.Text], []),
  'safeQueryWorker' : IDL.Func([IDL.Nat], [IDL.Opt(Worker)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchWorkersByArea' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
  'searchWorkersByAreaAndCategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Worker)],
      ['query'],
    ),
  'searchWorkersByAreaAndSubcategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Worker)],
      ['query'],
    ),
  'submitWorkerRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'unfeatureWorker' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CategoryMapping = IDL.Record({
    'category' : IDL.Text,
    'subcategories' : IDL.Vec(IDL.Text),
  });
  const JobPost = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'workType' : IDL.Text,
    'salary' : IDL.Text,
    'area' : IDL.Text,
    'description' : IDL.Text,
    'phone' : IDL.Text,
    'dateTime' : Time,
  });
  const WorkerStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Worker = IDL.Record({
    'id' : IDL.Nat,
    'status' : WorkerStatus,
    'verified' : IDL.Bool,
    'featured' : IDL.Bool,
    'subcategory' : IDL.Text,
    'area' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'experience' : IDL.Text,
    'workingHours' : IDL.Text,
    'category' : IDL.Text,
    'comments' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveJobPost' : IDL.Func([IDL.Nat], [], []),
    'approveWorker' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJobPost' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'featureWorker' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(CategoryMapping)], []),
    'getAllJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getApprovedJobs' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryBySubcategory' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getFeaturedWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getJobPostById' : IDL.Func([IDL.Nat], [IDL.Opt(JobPost)], ['query']),
    'getPendingJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
    'getPendingWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getSafeCategoryWorkers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Worker)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerById' : IDL.Func([IDL.Nat], [IDL.Opt(Worker)], ['query']),
    'getWorkersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
    'getWorkersBySubcategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Worker)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWorkerVerified' : IDL.Func([IDL.Nat], [], []),
    'rejectJobPost' : IDL.Func([IDL.Nat], [], []),
    'rejectWorker' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'repairDataIntegrity' : IDL.Func([], [IDL.Text], []),
    'safeQueryWorker' : IDL.Func([IDL.Nat], [IDL.Opt(Worker)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchWorkersByArea' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
    'searchWorkersByAreaAndCategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Worker)],
        ['query'],
      ),
    'searchWorkersByAreaAndSubcategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Worker)],
        ['query'],
      ),
    'submitWorkerRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'unfeatureWorker' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };